services:
  mongodb:
    image: mongo:7
    container_name: helpdesk_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  ai-service:
    build:
      context: .
      dockerfile: ./ai-service/Dockerfile
    container_name: helpdesk_ai
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ai_models:/app/models
    environment:
      - FLASK_ENV=production
      - PORT=3001
      - DATASET_PATH=/app/dataset
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3001/health')"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helpdesk_backend
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5000}
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/helpdesk_db}
      - JWT_SECRET=${JWT_SECRET:-change_this_to_a_very_long_secure_random_string_in_production}
      - JWT_EXPIRE=${JWT_EXPIRE:-7d}
      - AI_SERVICE_URL=${AI_SERVICE_URL:-http://ai-service:3001}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - SLA_CRITICAL_HOURS=${SLA_CRITICAL_HOURS:-1}
      - SLA_HIGH_HOURS=${SLA_HIGH_HOURS:-4}
      - SLA_MEDIUM_HOURS=${SLA_MEDIUM_HOURS:-24}
      - SLA_LOW_HOURS=${SLA_LOW_HOURS:-72}
      - EMAIL_USER=${EMAIL_USER:-tech16052006@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-iibr wjia auxt xrri}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_IMAP_HOST=${EMAIL_IMAP_HOST:-imap.gmail.com}
      - EMAIL_IMAP_PORT=${EMAIL_IMAP_PORT:-993}
    depends_on:
      mongodb:
        condition: service_healthy
      ai-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helpdesk_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mongo_data:
    name: helpdesk_mongo_data
  ai_models:
    name: helpdesk_ai_models
